### ISSUE TITLE
Review kind role and k8s playbook

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#163]
## TODO

- [x] Review kind playbook
- [x] Adapt the playbook to have the possibility to user it on a host and not a remote ssh host
- [x] Add the list of the images currently supported by `kind` - 0.8.1
- [x] Test it on macbook
