### ISSUE TITLE
Migrate the ingress role to use : ingress nginx controller

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#165]
## TODO

- [ ] Migrate the existing ingress role to use `ingress nginx controller` 
- [ ] Bump version to `2.6.0`
- [ ] Support both cases to install or remove ingress
- [ ] Add the opportunity to install the appropriate yaml file depending if we deploy on `kind` or `baremetal`
