### ISSUE TITLE
Improve the playbook to control python3, pip and virtualenv

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#169]
# TODO

- [ ] Improve the playbook to control python3, pip and virtualenv
- [ ] Add pre-tasks
- [ ] Check if python3, pip3 are installed
- [ ] Create the virtualenv and use it when we log on remotely
