### ISSUE TITLE
Migrate the installation process to a more recent OS as centos7 is outdated

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#239]
## Todo

- [ ] Docker vs Containerd
- [ ] Which OS (fedora vs centos stream)
- [ ] Review the list of the K8s tools and extend it with (k9s, kube ctx|ns|tree,helm, ...)
