### ISSUE TITLE
Review the rule checking the versions of k8s supported as we cannot install 1.22

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#253]
## TODO

Tasks to be done:

- [ ] Review the passstore_controller_inventory.yml playbook and rule checking the versions of k8s supported as currently we cannot install latest versions (>= 1.22). See [here](https://github.com/snowdrop/k8s-infra/blob/fef6e62834ccdf20b6706105e5ad4eecb5ca9ffb/ansible/playbook/passstore_controller_inventory.yml#L37-L41)
- [ ] Update the hosts.yml [file ](https://github.com/snowdrop/k8s-infra/blob/df2c2241a832b795a1b41bae68ccd3f5bb29c4e4/ansible/inventory/hosts.yml) as it only refers k8s versions from 1.15 to 1.21
- [ ] Check documentation such as by example this [page](https://github.com/snowdrop/k8s-infra/blob/cb59d1df0f494ee7223ff0ae1dae4221de1c9739/ansible/playbook/README.md#passstore_controller_inventory)
